### ISSUE TITLE
questions regarding the mapping between joint NAME and marker id (body_tracking_data)

### ISSUE THREAD

**Issue by ghost** [microsoft/Azure_Kinect_ROS_Driver#113]
Hello all,

I'm trying to get different joint positions in the camera frame based on the body tracking data. I wonder what would be the mapping between the marker ID and **joint NAME**? **For example, if I have 120 as the marker ID, what would be the joint name?** (I know the marker ID is 20 based on the discussion [here](https://github.com/microsoft/Azure_Kinect_ROS_Driver/issues/87)  )

I'm reading from the official joint index document as listed [`here`](https://docs.microsoft.com/en-us/azure/kinect-dk/body-joints). It looks like we have joint index from 0 to 32, so I assume there should be 33 marker IDs for one person. However, based on the discussion from issue 87 and the ros topic data, it looks like we only have 25 IDs published for each person. So my last question is why is it that we only have 25 marker IDs or how would one relate a given marker ID to a joint name?

Thank you for your help.

**Comment by RoseFlunder** [comment]
When using Body tracking SDK 1.0.0 there should be 32 markers for each person (joint id 0 to joint id 31).
In example ID 100 to 131 for the person with body id 1 . 200 to 231 for the person with body id 2 etc.

Joint id = Marker id % 100
Example: marker id 120 means body id 1 and joint id 20. According to the docs this is the "Ankle left" joint.

If you have less joints you may have installed an older version of the body tracking sdk because some joints are additions in newer versions.

Edit:
This is also described in the topics section of the usage guide:
https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/melodic/docs/usage.md#topics

**Comment by ghost** [comment]
Thank you. I have updated my body tracking lib and now I have 32 markers. So is it safe to assume for a given marker ID, the corresponding joint can be found based on this mapping [(`here`](https://docs.microsoft.com/en-us/azure/kinect-dk/body-joints))? For example, marker ID 102 means SPINE_CHEST. 

Appreciate your quick response.

**Comment by RoseFlunder** [comment]
Yes thats correct.
We use the body id and joint id from the sdk to calculate the marker id and you can always reverse the calculation to get the original body id and joint id from the sdk as explained.
