### ISSUE TITLE
Documented FPS are wrong when using kinect_rgbd.launch

### ISSUE THREAD

**Issue by NFiedler** [microsoft/Azure_Kinect_ROS_Driver#221]
**Describe the bug**
In the documentation, it is claimed, that the cameras FPS default to 5. While this is true for the driver.launch file, the kinect_rgbd.launch defaults to 30 FPS. 

I would like to fix it via a PR but I am not sure whether to change the default FPS in the kinect_rgbd.launch,  adapt the documentation for both files, or adapt the documentation, and driver.launch to 30 FPS.

**Comment by ooeygui** [comment]
Hi there,
Thanks for the question. We originally changed the driver launch file, as there were performance concerns in the general case. The Kinect can easily overwhelm a robot with data - most of which will likely go unused.  Our expectation is that these parameters will be adapted by the user as they tune their solution.   

We've opted to change defaults for the general case - but this cases was missed.
Documentation is always appreciated.

**Comment by christian-rauch** [comment]
This is my "fault". I added the `kinect_rgbd.launch` and added:
https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/f82f4bba2fa50e66b426de5df6e62fb7bc481d40/launch/kinect_rgbd.launch#L45
because you usually want to have the highest framerate available for robotic applications. I think arbitrarily restricting the framerate to a low 5Hz does not make sense and I would personally prefer if the `driver.launch` launch also uses the highest possible framerate.

**Comment by amelhassan** [comment]
Our customer support data from github issues on this site indicates that the vast majority users are using lower performance systems. Our defaults should reflect this, with the option of also running high performance.
