### ISSUE TITLE
Integrate the body tracking data to ROS

### ISSUE THREAD

**Issue by lesterlo** [microsoft/Azure_Kinect_ROS_Driver#45]
**Is your feature request related to a problem? Please describe.**
No, just a feature request

**Describe the solution you'd like**
Could we integrate the body tracking data to ROS system which can display the joint data on RViz and utilize the joint data through on difference ROS module?

Also, I want to use the ROS system to record the body movement data.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by RoseFlunder** [comment]
I think they are already working on it because they included a modified k4a.hpp in their repo, so that the C++ sensor API can be used with the C-API from the body tracking SDK.

However, I needed this myself and forked this repo to integrate bodytracking and other things until its officially integrated.
If you need it before the official release too, you can take a look at this branch of my repo:
https://github.com/RoseFlunder/Azure_Kinect_ROS_Driver/tree/feat/body-tracking-multi-kinect-2

I updated the usage.md and driver.launch with the additional parameters.
The parameter "body_tracking_enabled" controls if the joint positions will be published.
The positions will be published as a marker array and can be visualized in RViz.

For a multi kinect setup to work properly you will need an additional node that provides transform for the different kinect frames to a parent frame. Otherwise you won't have a valid tf tree if you start the driver.launch multiple times (each with a different tf_prefix of course).

Moreover I added parameters to specify an absolute path to a mkv recording file to open instead of a device together with a parameter recording_loop_enabled to rewind the recording and play it in a endless mode when the playback reaches the end of file.

Feel free to use or fork it.

**Comment by skalldri** [comment]
@RoseFlunder : are you interested in merging that code back into this mainline repo? You've got lots of great work there that resolves some of the open issues we have here (body tracking, playback support).

**Comment by RoseFlunder** [comment]
Sure, I would be glad to help.
I just need some time to seperate the things into single pull requests I guess.

**Comment by skalldri** [comment]
I'm also happy to take on the task of merging your branch back into the mainline repo if you want. I can put you on as a reviewer when I've got something put together.

**Comment by RoseFlunder** [comment]
@skalldri 
I already made a pull request for the playback functionality which you can review and test.
I used the C-API because the C++ API is not yet public in the Sensor SDK 1.1.0

Could be rewritten to the C++ API at a later point in time when 1.2.0 is released but shouldn't be a lot of work.

I will make another pull request for body tracking support soon.

**Comment by lesterlo** [comment]
@RoseFlunder 
Thanks, I will try your repo first.

**Comment by skalldri** [comment]
This was previously fixed.
