### ISSUE TITLE
Publish RGB pointclouds beyond the texture 

### ISSUE THREAD

**Issue by shuntaraw** [microsoft/Azure_Kinect_ROS_Driver#51]
**Is your feature request related to a problem? Please describe.**
Currently, RGB points are reconstructed only from the depths that have non-zero texture colors. Given that the depth camera has significantly wider FoV, it would be nice to have an option to publish all points including those that are not covered by the texture. 

**Describe the solution you'd like**
A potential implementation would be to publish all points regardless of the texture, and the points without texture can be colored in black. This is the approach adopted in realsense2_camera https://github.com/IntelRealSense/realsense-ros  

**Describe alternatives you've considered**
The points without texture may be colored in other colors, or a user-specified value.

**Comment by skalldri** [comment]
To do this, we would need to re-implement the Azure Kinect SDK transform functions, since they don't support what you're describing. While that's doable, it's not something that I'm planning on pursuing.

There are also alternative ways to do this that don't involve modifying this driver: for example, the depth-to-RGB registration could be done by an external node (like `depth_image_proc/register`) and that node could produce the point cloud you're looking for. You could also combine a point cloud produced by `depth_image_proc/register` with the point cloud from `/points2` to get a restricted-view RGB point cloud and unrestricted view monochrome point cloud.
