### ISSUE TITLE
Kinect timestamps and ros::Time::now() drift appart

### ISSUE THREAD

**Issue by skalldri** [microsoft/Azure_Kinect_ROS_Driver#57]
**Describe the bug**
Over time, ROS Time and Kinect time appear to drift appart. This may impact the timestamping solution implemented in #21 .

**To Reproduce**
Leave the ROS node running overnight. Observe that timestamps drift significantly over long periods of time.

**Expected behavior**
Timestamps should remain relatively consistent over long periods of time.

**Logs**
Please provide relevant logs to help diagnose your issue. To assist in debugging, please enable *info* level logging of the Azure Kinect Sensor SDK and attach any logs you have to this issue.
See [k4atypes.h](https://github.com/Microsoft/Azure-Kinect-Sensor-SDK/blob/feecae0456511ac734287571b101d10fd7292673/include/k4a/k4atypes.h#L184) for how to enable logs.

Please also enable *DEBUG* level logging of the ROS node.
See [roscpp/Overview/Logging](http://wiki.ros.org/roscpp/Overview/Logging) for how to enable ROS DEBUG logs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu]
 - Version [e.g. Version 1903, 18.04]

**Additional context**

**Comment by RoseFlunder** [comment]
The sensor sdk 1.2.0 is released now, tho the debian/ubuntu package comes next week.
With the new version we have new API to get a image system timestamp instead of a device timestamp calculated from the SDK:
[https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/608](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/608)

But looks that they didn't provide such a method for the IMU sample unfortunately.

Maybe we can start to rewrite this logic with new API.
Use the new API for image timestamps.
Use the current approach only for IMU. So this "startTime" is only used by the IMU thread. No potential race condition, no need to protect access to start_time_ variable.

**Comment by helenol** [comment]
@RoseFlunder Great about the new features provided in the SDK! However, there's a big potential problems with your proposed solution: the IMU and image time-stamps will then drift apart, negating the whole purpose of the of having an IMU on the same hardware clock as the image exposure.
I think a better solution would be to provide access to the mapping between the system and device time through the SDK, not just for a specific image.
A better interim solution would be to use some standard techniques to filter the device timestamps over time, such as: https://github.com/ethz-asl/cuckoo_time_translator

**Comment by RoseFlunder** [comment]
@helenol
I understand. I also learned that the system timestamp from the SDK is not a mapping based on the device stamp.
Instead its defined otherwise:
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/include/k4a/k4a.h#L899

> The system timestamp is captured at the moment host PC finishes receiving the image.

I guess we don't want this time right?

The device timestamp on the other hand is defined as follows:
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/include/k4a/k4a.h#L873
> Returns the device timestamp of the image, as captured by the hardware. Timestamps are recorded by the device and represent the mid-point of exposure. They may be used for relative comparison, but their absolute value has no defined meaning.

Your proposed time translator looks good

**Comment by bnjff** [comment]
The translator would be very useful. In our application, we need to sync the images with the proximity sensor triggering. With the current implementation, the camera's timestamps are lagging by a few hundred ms from the beginning (i.e. not just drifting over time), and the images cannot be synced correctly by message_filters. Since we're not using IMU, we solved it by reverting to the system time-based timestamps.

**Comment by Brent-A** [comment]
FYI, for @wes-b who works on the timestamps in the SDK.

**Comment by helenol** [comment]
Update from some triage... Doing tests on linux between device (AKDK hardware) timestamps, system (usb bus arrival afaik) timestamps, and the constant offset from start that we currently use.
I seem to experience a drift of about 1 ms/minute between device timestamp and "real" timestamp.

Did this by comparing image system timestamp + monotonic to realtime clock offset (evaluated at that iteration) vs. device timestamp + start_time from ROS.
The difference between the two grows steadily at about 1 ms per minute or so on my machine, which frankly is substantial.

Just need to do a portable between Windows and Linux solution for getting the monotonic-to-realtime clock conversion (I guess this is partially done in k4a with QueryPerformanceCounter(), and trivial in linux) and hopefully this should solve some of the problems.

Doing this approach should also solve the huge timestamp lagging issues @bnjff mentioned.
