### ISSUE TITLE
ROS launch configuration for cartographer

### ISSUE THREAD

**Issue by brookman** [microsoft/Azure_Kinect_ROS_Driver#58]
Hi. I am new to Kinect/ROS and currently trying to get a (SLAM) 3D pose from the device. I have found the launch configuration for rtabmap_ros but didn't manage to install it on windows. I was recommended to use cartographer_ros which I got running.
Now I am struggling with the configuration. Cartographer needs a .lua as well as a .launch configuration. For beginners like me it would be tremendously helpful to have an example configuration for cartographer similar to the one in slam_rtabmap.launch.

**Comment by skalldri** [comment]
I've previously played around with cartographer, but didn't have much success. I found cartographer to be really, _really_ challenging to tune. I couldn't get cartographer working in a way I was happy with, so I decided not to publish any sample launch files as part of this repo.

I can probably dig up the old configuration files for you and post a Gist to get you started: because of the poor quality, I don't want to put them in the main repo, since people will expect that to "just work", but I'm happy to post them here with the caveat that I couldn't get good results from them.

I'll go dig up the files later today.

**Comment by brookman** [comment]
Thank you for the reply. I have spent several days trying to configure cartographer. But my success is limited. I have also tried to down-sample the  point cloud with pcl. Here are some of my (broken) setting files: https://gist.github.com/brookman/28858616394202885a1047dadb16d78d

Edit: By the way: Is it possible to run rtabmap_ros on Windows? I wasn't able to do so after trying a few hours. That is the reason why I switched to cartographer.

**Comment by skalldri** [comment]
To my knowledge, rtabmap_ros is not compiled as part of the ROS on Windows 10 builds, and it seems like a pretty complicated project to try and build from scratch.

Good news though: after the fix for #36, Cartographer seems to be working somewhat better. Still not great, but definitely better than the jumpy tracking I was seeing previously.

Here are some files I used to get ~30 FPS poses out of Cartographer. The machine running Cartographer wasn't all too powerful, but it was running on Linux. 

I can't really vouch for the quality of the LUA configuration file: it's the result of a few weeks of randomly tweaking settings to see what worked best. It works, but there's probably lots of room for improvement.

Put the .lua file in a folder called "config" in the ROS node directory, then put the .launch files in the launch folder. Then do `roslaunch azure_kinect_ros_driver slam_cartographer.launch`.

[CartographerConfig.zip](https://github.com/microsoft/Azure_Kinect_ROS_Driver/files/3548386/CartographerConfig.zip)

**Comment by brookman** [comment]
Thank you very much for sharing your configs. I had to switch to 15fps and still use the pcl to down-sample the point cloud. But then I was able to do some mapping in real time! https://youtu.be/B0BnGLpXWt0
The device pose is for some reason still very jumpy though.
